repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.2
  hooks:
  - id: ruff
    args:
    - --fix
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.10.1"
  hooks:
  - id: mypy
    args:
    - --ignore-missing-imports
    - --follow-imports=silent
    additional_dependencies:
    - types-all
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0 # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
